apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: sns2nm9le-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sns2nm9le-python 
  name: sns2nm9le-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: sns2nm9le-python 
